### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by sts-ryan-holton** [snoeren-development/laravel-discord-webhook-channel#13]
After receiving (so far) little support from the official discord notification channel, I've switched to this for Discord notifications as I need webhook support. Pleased to announce that implementing it just now in Laravel 8 on PHP 7.4 works lovely - but is it maintained for the long term?

**Comment by MSnoeren** [comment]
Hi there! Yes, I'm maintaining it for the long term. Most releases are dependency and security updates though.
