### ISSUE TITLE
Queueing support

### ISSUE THREAD

**Issue by zepfietje** [snoeren-development/laravel-discord-webhook-channel#6]
It seems like this package currently doesn't support queued notifications?

**Comment by MSnoeren** [comment]
Hi @zepfietje! It should support queueing. Does your notification implement Laravel's `ShouldQueue` and `Queueable`?

**Comment by zepfietje** [comment]
Yes, and it works fine locally. However, running in production it fails with the following exception:
`Driver [SnoerenDevelopment\DiscordWebhook\DiscordWebhookChannel] not supported.`

**Comment by MSnoeren** [comment]
Strange. That often means that namespaces are not correctly configured as Laravel cannot find them. Can you optimize your local environment and try again locally or clear the application cache in production? Maybe it's a caching issue.

**Comment by zepfietje** [comment]
What do you mean by "optimize your local environment"?

**Comment by MSnoeren** [comment]
The `php artisan optimize` and `php artisan optimize:clear` commands. They cache the autodiscovered packages too.

**Comment by zepfietje** [comment]
After running `php artisan optimize` locally, no notifications come through. Both queued and not.

**Comment by MSnoeren** [comment]
I verified it working locally both queued, unqueued, optimized and non-optimized. In all cases the notification was sent. Can you check if you;
1. use `DiscordWebhookChannel::class` in your `via` method of your notification.
2. Implement the `toDiscord` method in your notification.
3. Implement the `routeNotificationForDiscord` method on your notifiable model (often User or Team).
4. Have a working webhook URL for Discord.

If none of it works, I would try to dump the composer autoload files again to ensure the class is autoloaded. Also, some (example) code would help ;)

**Comment by zepfietje** [comment]
It's working locally now (not sure what fixed it).
However, in production (or staging) I can't seem to get it to work.
Also tried running `composer dump-autoload` and `php artisan optimize:clear` there.

I'm not doing anything special with the notification, so probably it's not related to this package (but rather a caching issue indeed).

**Comment by zepfietje** [comment]
When running `php artisan package:discover` I found that this package is not listed.
Could this be the cause?

**Comment by MSnoeren** [comment]
The package should be autodiscovered. It was in my test setup. Are you using Laravel 5.5 or higher?

**Comment by zepfietje** [comment]
Yep, latest Laravel version.

**Comment by zepfietje** [comment]
@MSnoeren I'm still running into this issue.
Everything works fine locally (queued and not queued), but in production it only works when not queueing the notification. When queuing, I get the exception I posted earlier:
`Driver [SnoerenDevelopment\DiscordWebhook\DiscordWebhookChannel] not supported.`

**Comment by zepfietje** [comment]
Okay, finally solved it by running `php artisan queue:restart`.
